baseURL = "https://ningonone.github.io"
languageCode = "zh-CN"
title = "NINGO's Blog"
theme = "yinyang"

[params]
# disqus = "joway" # disqus account name
headTitle = "NINGO" 
description = "store some memories here..." 
extraHead = ''
mainSections = ["posts"]
galleryPassword = "106078"
favicon = "/static/images/avatar.png"

[[params.socials]]
name = "Post"
link = "/index.html"

[[params.socials]]
name = "Movies"
link = "/movies/"


[[params.socials]]
name = "Gallery"
link = "/gallery/"
