baseURL = "https://example.com"
languageCode = "zh-CN"
title = "Example YinYong Blog"
theme = "yinyang"

[params]
# disqus = "joway" # disqus account name
headTitle = "NINGO" 
description = "store some memories here..." 
extraHead = ''
mainSections = ["posts"]
galleryPassword = "106078"


[[params.socials]]
name = "Post"
link = "/index.html"
target = "_self"

[[params.socials]]
name = "Gallery"
link = "/gallery/"
target = "_self"
